version: '3.8'

services:
  nestjs:
    build: nestjs
    image: nestjs:idonado
    container_name: nestjs
    ports:
      - 3000:3000
    networks:
      - app_default
#    expose:
#      - "5432"
#    volumes:
#      - app_nestjs:/
    restart: always

  reactjs:
    build: reactjs
    image: reactjs:idonado
    container_name: reactjs
    ports:
      - 3001:80
    networks:
      - app_default
#    expose:
#      - "5432"
#    volumes:
#      - app_reactjs:/usr/src/app
    restart: always

#volumes:
#  
#  app_nestjs:
#    name: app_nestjs_volume
#    driver_opts:
#      type: 'none'
#      o: 'bind'
#      device: /home/$USER/Desktop/local_pong/nestjs
#volumes:
#
#  app_reactjs:
#    name: app_reactjs_volume
#    driver_opts:
#      type: 'none'
#      o: 'bind'
#      device: /home/$USER/app_reactjs_volume

networks:

  app_default:
    driver: bridge