version: '3.8'

services:
  nestjs:
    build: nestjs
    image: nestjs:henkies
    container_name: nestjs
    ports:
      - 3000:3000
      - 5555:5555
    networks:
      - app_default
#    expose:
#      - "5432"
    volumes:
      - pong_nestjs:/nestjs
    restart: always

  reactjs:
    build: reactjs
    image: reactjs:henkies
    container_name: reactjs
    ports:
      - 3001:3001
    networks:
      - app_default
#    expose:
#      - "5432"
    volumes:
      - pong_reactjs:/reactjs
    restart: always

  pongdb:
    image: postgres:14.2
    container_name: pongdb
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=user123
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=nestdb
    networks:
      - app_default
    restart: always

  testdb:
    image: postgres:14.2
    ports:
      - 5435:5432
    container_name: testdb
    environment:
      - POSTGRES_USER=user123
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=nestdb
    networks:
      - app_default
    restart: always

volumes:
  
  pong_nestjs:
    name: pong_nestjs_volume
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/$USER/pong_nestjs

  pong_reactjs:
    name: pong_reactjs_volume
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/$USER/pong_reactjs

networks:

  app_default:
    driver: bridge