version: '3.8'

services:
  pongdb:
    image: postgres:14.2
    container_name: pongdb
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=user123
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=nestdb
    networks:
      - app_default
#    expose:
#      - "5432"
#    volumes:
#      - db:/var/lib/postgresql/data
    restart: always

  testdb:
    image: postgres:14.2
    ports:
      - 5435:5432
    container_name: testdb
    environment:
      - POSTGRES_USER=user123
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=nestdb
    networks:
      - app_default
    restart: always

#volumes:
#  
#  db:
#    name: db_volume
#    driver_opts:
#      type: 'none'
#      o: 'bind'
#      device: /home/$USER/pong_volume/db

networks:

  app_default:
    driver: bridge