import React from 'react';
import Head from 'next/head';
import styles from '../styles/Bootstrap.module.css';

function MainLayout({ children }: { children: React.ReactNode })
{
    return (
        // NAV
        <div>
                <Head>
                  <title>Pong</title>
                  <meta name="description" content="Generated by create next app" />
                  <link rel="icon" href="/favicon.png" />
                </Head>
                <div className={ styles["px-3"] + " " + styles["py-2"] + " " + styles["bg-dark"] + " " + styles["text-white"]}>
                  <div className={ styles.container }>
                    <div className={ styles["d-flex"] + " " + styles["align-items-center"] + " " + styles["justify-content-center"] + " " + styles["justify-content-lg-start"] }>
                      <a href="/" className={ styles["d-flex"] + " " + styles["align-items-center"] + " " + styles["my-2"] + " " + styles["my-lg-0"] + " " + styles["me-lg-auto"] + " " + styles["text-white"] + " " + styles["text-deconration-none"] }>
                      42
                      </a>

                      <ul className={ styles["nav"] + " " + styles["col-12"] + " " + styles["col-lg-auto"] + " " + styles["my-2"] + " " + styles["justify-content-center"] + " " + styles["my-md-0"] + " " + styles["text-small"] }>
                        <li>
                          <a href="#" className={ styles["nav-link"] + " " + styles["text-secondary"] }>
                            Home
                          </a>
                        </li>
                        <li>
                          <a href="#" className={ styles["nav-link"] + " " + styles["text-white"] }>
                            Dashboard
                          </a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>

                { children }

                <div className={ styles.container }>
                  <div className={ styles["py-3"] + " " + styles["my-4"] }>
                    <ul className={ styles["nav"] + " " + styles["justify-content-center"] + " " + styles["border-bottom"] + " " + styles["pb-3"] + " " + styles["mb-3"] }>
                      <li className="nav-item"><a href="#" className={ styles["nav-link"] + " " + styles["px-2"] + " " + styles["text-muted"] }>Home</a></li>
                      <li className="nav-item"><a href="#" className={ styles["nav-link"] + " " + styles["px-2"] + " " + styles["text-muted"] }>Dashboard</a></li>
                    </ul>
                    <p className={ styles["text-center"] + " " + styles["text-muted"] }>© 2022 ft_transcendence, team henkies</p>
                  </div>
                </div>

        </div>
    );
}
export default MainLayout